# Generated by Django 4.2.1 on 2023-05-05 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_created_at_post_created_date_remove_post_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
