# Generated by Django 4.2.1 on 2023-05-08 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='product',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product',
            new_name='post',
        ),
    ]
